config/routes.rb
require "sidekiq/web"

TedxBrisbane::Application.routes.draw do
  root :to => "pages#index"

  get "/confirm/:token", to: "email_links#confirm"
  get "/decline/:token", to: "email_links#decline"
  get "/pay/:token", to: "email_links#pay"

  get "/payment/:token", to: "payments#new", as: "new_payment"
  post "/payments/:token/confirm" => "payments#confirm", as: "confirm_payment"

  get "/emails/:token" => "emails#content", as: "show_email"

  namespace :api do
    namespace :v1 do
      resources :attendees, only: [:create] do
        collection do
          get 'statistics'
        end
      end
    end
  end

  resources :attendees, only: :create

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  mount Sidekiq::Web => "/sidekiq" if Rails.env == "development"
end

app/models/payment.rb
class Payment < ActiveRecord::Base
  validates :attendee_id, :amount, :receipt_number, :masked_number, :card_type, presence: true
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :verify_attendee

  def new
    @token = params[:token]
  end

  def confirm
    PaywayConnector.make_payment!(attendee, params)
    redirect_to('/', notice: I18n.t("controllers.payments.success"))
  rescue Exceptions::TEDXErrorWithPredefinedMessage => e
    redirect_to(new_payment_path(params[:token]), notice: e.message)
  end

  private

  def verify_attendee
    unless attendee && attendee.received_invitation?
      redirect_to('/', notice: I18n.t("controllers.payments.invalid"))
    end
  end


  def attendee
    @attendee ||= Attendee.where(pay_token: decoded_token).first
  end

  def decoded_token
    Base64.urlsafe_decode64(params[:token]) rescue "null_token"
  end

end

app/views/payments/new.html.haml
%h1= "Purchasing a ticket for #{@attendee.email_address}"

= form_for :transaction, url: confirm_payment_path(token: @token), html: { id: "new_payment", autocomplete: "off" } do |f|

  .box

    %section#inputs

      %ol
        %legend Your details

        = f.fields_for :customer do |c|

          %li.half-width
            = c.label :first_name, "First Name"
            = c.text_field :first_name, value: @attendee.first_name

          %li.half-width
            = c.label :last_name, "Last Name"
            = c.text_field :last_name, value: @attendee.last_name

        %li
          = label_tag :student_amount,"Tickets cost: "
          = select_tag :student_amount, options_for_select([["$#{Event.price_in_dollars}", false],["$#{Event.price_in_dollars_for_student} for students", true]],
                                                               ["$#{Event.price_in_dollars}", false])
      %ol

        %legend Credit Card

        = f.fields_for :credit_card do |c|

          %legend.credit-cards
            = c.radio_button :type, 'master'
            %label.credit-card= image_tag 'icons/mastercard.png'
            = c.radio_button :type, 'visa'
            %label.credit-card= image_tag 'icons/visa.png'

          %li
            = c.label :number, "Number"
            = c.text_field :number

          %li.half-width
            = c.label :expiration_date, "Expiration Date (MM/YY)"
            = c.text_field :expiration_date

          %li.half-width
            = c.label :cvv, "CVV"
            = c.text_field :cvv

    %section#buttons
      %ol
        %li
          .submit-container
            = f.submit "Submit", class: 'btn btn-large'
          = link_to 'Cancel', root_path